services:

  fenrus:
    image: revenz/fenrus:latest
    container_name: fenrus
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./app/data:/app/data
    ports:
      - '8200:3000'
    restart: unless-stopped    
